# This is a basic workflow to help you get started with Actions

name: deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: install npm
        run: npm install
      - name: cd to website
        run: cd website
      - name: build
        run: npm run build --if-present
      - name: Sync
        env:
          dest: 'joematte@178.128.152.190:/var/www/the-anxious-turtle.com/html'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            ./build/* ${{env.dest}}
